name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd The-Weaver-s-Gift && npm ci
      - run: cd The-Weaver-s-Gift && npm run dev
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_THE_WEAVER_S_GIFT }}
          channelId: live
          projectId: the-weaver-s-gift
          entryPoint: The-Weaver-s-Gift
